// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateProduct() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"createProduct\" hx-post=\"/create-product\" hx-on::after-request=\"this.reset()\" hx-swap=\"none\" class=\"flex flex-col gap-4\"><p class=\"text-2x1 font-bold\">Crear Producto</p><input required type=\"text\" name=\"nombre\" placeholder=\"Nombre\" class=\"bg-slate-500 border-slate-700 p-1\"> <input required type=\"text\" name=\"codigo\" placeholder=\"Codigo de barra\" class=\"bg-slate-500 border border-slate-700 p-1\"> <input required type=\"text\" name=\"margen\" placeholder=\"Margen de venta\" class=\"bg-slate-500 border border-slate-700 p-1\"> <input required type=\"text\" name=\"precio\" placeholder=\"Precio Inicial\" class=\"bg-slate-500 border border-slate-700 p-1\"> <button type=\"submit\" class=\"bg-slate-500 bg-opacity-20 border border-slate-700\">Crear Producto</button></form><p hx-trigger=\"duplicateError from:body\" hx-get=\"/static/addProductDuplicate.html\" id=\"errorDupe\" class=\"text-red-600 text-center\"></p><p hx-trigger=\"invalidError from:body\" hx-get=\"/static/addProductInvalid.html\" id=\"errorInvalid\" class=\"text-red-600 text-center\"></p><p hx-trigger=\"insertError from:body\" hx-get=\"/static/addProductInsert.html\" id=\"errorUserInsert\" class=\"text-red-600 text-center\"></p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func CreateSale() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"crearUsuario\" hx-post=\"/create-user\" hx-confirm=\"Seguro que quiere crear este usuario?\" hx-on::after-request=\"this.reset()\" hx-swap=\"none\" class=\"flex flex-col gap-4 align-middle justify-center mx-20\"><p class=\"text-3xl font-bold\">Crear usuario</p><input required type=\"text\" name=\"username\" placeholder=\"usuario\" class=\"bg-slate-500 border-slate-700 p-1\"> <input required type=\"password\" name=\"password\" placeholder=\"password\" class=\"bg-slate-500 border-slate-700 p-1\"> <select required name=\"privilege\" class=\"bg-slate-500 border-slate-700 p-1\"><option value=\"admin\">Administrador</option> <option value=\"manager\">Gerente</option> <option value=\"user\">Usuario</option></select> <button type=\"submit\">Crear Usuario</button></form><p hx-trigger=\"duplicateError from:body\" hx-get=\"/static/addUserDuplicate.html\" id=\"errorDupe\" class=\"text-red-600 text-center\"></p><p hx-trigger=\"invalidPrivilegeError from:body\" hx-get=\"/static/addUserInvalid.html\" id=\"errorInvalidPriv\" class=\"text-red-600 text-center\"></p><p hx-trigger=\"insertError from:body\" hx-get=\"/static/addUserInsert.html\" id=\"errorUserInsert\" class=\"text-red-600 text-center\"></p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func CreatePurchase() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"crearUsuario\" hx-post=\"create-user\" hx-confirm=\"Seguro que quiere crear este usuario?\" hx-on::after-request=\"this.reset()\" hx-swap=\"none\" class=\"flex flex-col gap-4 align-middle justify-center mx-20\"><p class=\"text-3xl font-bold\">Crear usuario</p><input required type=\"text\" name=\"username\" placeholder=\"usuario\" class=\"bg-slate-500 border-slate-700 p-1\"> <input required type=\"password\" name=\"password\" placeholder=\"password\" class=\"bg-slate-500 border-slate-700 p-1\"> <select required name=\"privilege\" class=\"bg-slate-500 border-slate-700 p-1\"><option value=\"admin\">Administrador</option> <option value=\"manager\">Gerente</option> <option value=\"user\">Usuario</option></select> <button type=\"submit\">Crear Usuario</button></form><p hx-trigger=\"duplicateError from:body\" hx-get=\"/static/addUserDuplicate.html\" id=\"errorDupe\" class=\"text-red-600 text-center\"></p><p hx-trigger=\"invalidPrivilegeError from:body\" hx-get=\"/static/addUserInvalid.html\" id=\"errorInvalidPriv\" class=\"text-red-600 text-center\"></p><p hx-trigger=\"insertError from:body\" hx-get=\"/static/addUserInsert.html\" id=\"errorUserInsert\" class=\"text-red-600 text-center\"></p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
