// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><head><script src=\"/static/htmx.min.js\"></script><link rel=\"stylesheet\" type=\"text/css\" href=\"/static/tailwind.css\"><title>Administracion</title></head><body id=\"fullPage\" class=\"bg-slate-600 font-sans text-slate-200 text-lg m-20\"><div id=\"loginScreen\" class=\"justify-center align-middle\"><form id=\"loginForm\" hx-post=\"/create-session\" class=\"flex flex-col gap-4 mx-10 my-16 align-middle\"><p class=\"text-3xl justify-center text-center\">Login</p><input type=\"text\" name=\"username\" placeholder=\"Username\" class=\"text-slate-600\"> <input type=\"password\" name=\"password\" placeholder=\"Password\" class=\"text-slate-600\"> <button type=\"submit\" class=\"size-5\">Login</button><p id=\"error\" class=\"text-red-600 justify-center align-middle text-center\" hx-get=\"/static/login-error.html\" hx-trigger=\"loginFailed from:body\" hx-swap=\"innerHTML\"></p></form></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
