package handlers

import (
	"github.com/labstack/echo/v4"
)

func DefineRouting(e *echo.Echo) {
	e.GET("/", IndexEntranceHandler)
	e.POST("/", IndexEntranceHandler)
	e.GET("/login", LoginHandler)
	e.PUT("/views/tables", ProductsTableHandler)
	e.PUT("/views/ventas", SalesPutHandler)
	e.PUT("/views/loss", LossPutHandler)
	e.PUT("/views/compras", PurchasesPutHandler)
	e.PUT("/views/crear_usuario", UsersPutHandler)
	e.POST("/views/salir", SalirPostHandler)
	e.POST("/create-session", CreateSessionHandler)
	e.POST("/create-user", CreateUserHandler)
	e.POST("/create-product", CreateProductHandler)
	e.PUT("/disableProduct", DisableProductHandler)
	e.PUT("/enableProduct", EnableProductHandler)
	e.PUT("/modifyProductForm", ModifyProductFormHandler)
	e.POST("/modifyProduct", ModifyProductHandler)
	e.POST("/small-table-search", SmallTableSearchHandler)
	e.GET("/get-sales-table", TablesSalesHandler)
	e.GET("/get-loss-table", TablesLossHandler)
	e.POST("/get-sales-table-detail", TablesSalesDetailHandler)
	e.POST("/get-loss-table-detail", TablesLossDetailHandler)
	e.POST("/start-sale", StartSaleHandler)
	e.POST("/start-loss", StartLossHandler)
	e.POST("/create-sale", CreateSaleHandler)
	e.POST("/create-loss", CreateLossHandler)
	e.POST("/complete-sale", CompleteSaleHandler)
	e.POST("/complete-loss", CompleteLossHandler)
	e.POST("/calculateTotal", calculateTotalSaleHandler)
	e.GET("/get-purchase-table", TablesPurchasesHandler)
	e.POST("/create-purchase", CreatePurchaseHandler)
	e.POST("start-purchase", StartPurchaseHandler)
	e.POST("/small-table-search-purchase", SmallPurchaseTableSearchHandler)
	e.POST("/complete-purchase", CompletePurchaseHandler)
	e.POST("/calculateTotalPurchase", calculateTotalPurchaseHandler)
	e.PUT("/views/stats", StatsMainScreenHandler)

	e.POST("/tableSearch", TableSearchHandler)

	e.POST("/mostSold", ViewMostSoldProductHandler)
	e.POST("/pSalesToDate", CalculateSalesOfProductInTimespan)
	e.POST("/dpSalesToDate", CalculateProductDeltaInTimespan)
	e.POST("/pHighestIncome", CalculateMostProfitableProductInTimespan)
	e.POST("/incomeToDate", CalculateProfitsOfProductInTimespan)
	e.POST("/incomeVar", CalculateProfitDeltaInTimespan)
	e.POST("/salesToDate", CountSalesInTimespan)
	e.POST("/dSalesToDate", CalculateSaleAmountDeltaTimespan)
	e.POST("/pExpense", CalculateMoneySpentProduct)
	e.POST("/pExpenseVar", CalculateDeltaMoneySpentProduct)
	e.POST("/expense", CalculateMoneySpentTimespan)
	e.POST("/expenseVar", CalculateMoneySpentDeltaTimespan)

	e.POST("/testingGraph", TestingStatGraph)
}
